import { Link } from 'react-router-dom';
import liveFeedImage from '../assets/live-feed.png';
import pathVisualizationImage from '../assets/path-visualization.png';
import analyticsDashboardImage from '../assets/analytics-dashboard.png';

function Home() {
  return (
    <main className="p-6 space-y-8">
      <section className="text-center bg-blue-100 p-8 rounded-lg shadow-md">
        <h1 className="omegawatch">OMEGAWATCH</h1>
        <p className="text-gray-700">
          Our mission is to find efficient paths and provide real-time insights during disasters using drones and machine learning.
        </p>
      </section>

      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Link to="/live-feed">
        <div className="bg-white p-6 rounded-lg shadow-lg text-center hover-effect bg-cover bg-center h-80 relative flex items-center justify-center">
          <div className="overlay" style={{ backgroundImage: `url(${liveFeedImage})` }}></div>
          <div className="home-center">
          <h2 className="text-xl font-semibold mb-2 relative z-10">Live Drone Feed</h2>
          <p className="text-gray-600 relative z-10 description">View the real-time video feed captured by the drone.</p>
          </div>
        </div>
        </Link>
        <Link to="/path-visualization">
        <div className="bg-white p-6 rounded-lg shadow-lg text-center hover-effect bg-cover bg-center h-80 relative flex items-center justify-center">
        <div className="overlay" style={{ backgroundImage: `url(${pathVisualizationImage})` }}></div>
        <div className="home-center">
          <h2 className="text-xl font-semibold mb-2 relative z-10">Path Visualization</h2>
          <p className="text-gray-600 relative z-10 description">Track the efficient path generated by our ML model on the map.</p>
          </div>
        </div>
        </Link>
        <Link to="/analytics">
        <div className="bg-white p-6 rounded-lg shadow-lg text-center hover-effect bg-cover bg-center h-80 relative flex items-center justify-center">
        <div className="overlay" style={{ backgroundImage: `url(${analyticsDashboardImage})` }}></div>
        <div className="home-center">
          <h2 className="text-xl font-semibold mb-2 relative z-10">Analytics Dashboard</h2>
          <p className="text-gray-600 relative z-10 description">Get actionable insights based on drone data and RFID tags.</p>
          </div>
        </div>
        </Link>
      </section>
    </main>
  );
}

export default Home;
